### ISSUE TITLE
File Not Found... 

### ISSUE THREAD

**Issue by ghost** [thaihungle/SAM#1]
Please could I know from where I need to download the files required to execute this? Please help. 
![Inkedfilenotfound_LI](https://user-images.githubusercontent.com/74771222/99795720-46331e80-2b52-11eb-8ecd-920ebe44adc9.jpg)

**Comment by thaihungle** [comment]
Hi, 
Please find the dataset here https://pytorch.org/text/_modules/torchtext/datasets/babi.html

**Comment by ghost** [comment]
I had downloaded the files in this link https://github.com/siddk/entity-network/tree/master/tasks and then put them in a folder named 'data' and put that folder into 'babi' in here : https://github.com/thaihungle/SAM/tree/master/babi   .... and i executed this command : python run_all_babi.py  and I got the following error:
![strip2](https://user-images.githubusercontent.com/74771222/99929337-dcde2600-2d72-11eb-9c11-7c2463c67198.png)

It says NoneType object no attribute 'strip',... so nothing is stored in token? I don't know what I'm doin wrong. Please help. Thanks .

**Comment by thaihungle** [comment]
This error is new to me. I see you are reading pik files. Did you download the raw dataset and run the code with raw data first? It should generate the valid pik for other runs. 
Also, it's best to use torch 1.0.0.

**Comment by ghost** [comment]
Please may I know from where I can download the raw dataset? In this link you had shared before : https://pytorch.org/text/_modules/torchtext/datasets/babi.html , I'm not sure if I'm supposed to paste it in some code file that's already there and run it ?

**Comment by thaihungle** [comment]
The official raw dataset is here http://www.thespermwhale.com/jaseweston/babi/tasks_1-20_v1-2.tar.gz
You can find the data folder en-valid-10k 
Put it under your ./babi/data/

**Comment by ghost** [comment]
I did as per your instructions. I downloaded the raw dataset and put the necessary files under ./babi/data.... Now Im getting the following error:
![babi_error](https://user-images.githubusercontent.com/74771222/100236814-2a65b900-2f54-11eb-88a6-12e206db34e1.png)
 
So I went and looked into the data folder, and the pik files weren't generated.
What do I do now? Please help!!!

**Comment by thaihungle** [comment]
I use python 3.6 and this only yields a warning (see attached image)
Maybe you should try python 3.6 or modify the code to ignore empty string.
![image](https://user-images.githubusercontent.com/3315061/100396816-b681f880-309a-11eb-9c6f-0099e61747f1.png)
