### ISSUE TITLE
Code for reinforcement learning

### ISSUE THREAD

**Issue by eugenelet** [thaihungle/SAM#2]
Hi there,

Thanks for sharing the code for your interesting work!

Is it possible to share the code used for reinforcement learning in your experiments? Would like to check the results. Thanks!

Eugene

**Comment by thaihungle** [comment]
Hi Eugene,

As per your request, I will create a new branch and upload my code for RL experiments. Now I am a bit busy, I will do later whenever I have time. 

The code for RL is built up on this repo https://github.com/dgriff777/rl_a3c_pytorch
Basically, I just replaced LSTM with STM. 

Hung

**Comment by eugenelet** [comment]
Hi Hung,

Thanks for sharing the repo for the RL experiments. Looking forward to the release of the RL code for STM.

Eugene

**Comment by thaihungle** [comment]
Hi Eugene,

For simplicity, I have added the code for RL task in master branch. Hope this helps.

Cheers,

Hung

**Comment by eugenelet** [comment]
Hi Hung,

Thanks for sharing the code for RL task. It's a great contribution to the ML community ;) 

Eugene
