### ISSUE TITLE
Possibly Incorrect Learning Rate

### ISSUE THREAD

**Issue by mind-matrix** [thaihungle/SAM#3]
Hey. So I was going through the bAbI model config and the learning rate is fixed at **0.0006** whereas the paper suggests using a learning rate of **0.006** which is 10x the config learning rate. Is this a typo or am I missing something?

**Comment by thaihungle** [comment]
Sorry, this is a typo in the paper. 
The correct one is in the code.

**Comment by mind-matrix** [comment]
Thanks.
