### ISSUE TITLE
Meaning of input and output of STM module

### ISSUE THREAD

**Issue by wenxiaopeng-del** [thaihungle/SAM#4]
Hello, I am very interested in your paper, but I do not know much about the content in this direction. I have a question to ask you: is it possible to input a three-dimensional tensor and represent (output, item memory, relational memory) in the STM module? And the three dimensional tensor of the input, what does each dimension of the data represent?

**Comment by thaihungle** [comment]
I don't really understand your question. 
The input to STM is sequences of vectors. The item memory and relational memory are automatically built upon the input so they should not be treated as the input. 
Regarding the 3 dimensions of the input tensor, they should be batch size, sequence length and vector size. 
The final output can be also sequences of vectors.
